fixtures:
  repositories:
    apache:
      repo: 'git://github.com/puppetlabs/puppetlabs-apache.git'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    concat:
      repo: 'https://github.com/ripienaar/puppet-concat.git'
  symlinks:
    passenger: "#{source_dir}"
