fixtures:
  repositories:
    apache:
      repo: 'git://github.com/puppetlabs/puppetlabs-apache.git'
    concat:
      repo: 'git://github.com/puppetlabs/puppetlabs-concat.git'
  symlinks:
    passenger: "#{source_dir}"
