fixtures:
  repositories:
    apache:
      repo: 'git://github.com/puppetlabs/puppetlabs-apache.git'
    concat:
      repo: 'git://github.com/puppetlabs/puppetlabs-concat.git'
    gcc:
      repo: 'git://github.com/puppetlabs/puppetlabs-gcc.git'
    make:
      repo: 'git://github.com/cmroddy/puppet-make.git'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    passenger: "#{source_dir}"
