name 'puppetlabs-passenger'
version '0.0.3'
source 'git://github.com/puppetlabs/puppetlabs-passenger.git'
author 'puppetlabs'
license 'ASL 2.0'
summary 'Passenger Module'
description 'Manages Passenger (mod_rails)'
project_page 'http://github.com/puppetlabs/puppetlabs-passenger'

dependency 'puppetlabs/apache', '>= 0.0.3'
dependency 'puppetlabs/gcc', '>= 0.0.1'
dependency 'puppetlabs/ruby', '>= 0.0.1'
